source 'http://rubygems.org'

gem 'rake'
gem 'sinatra', '1.3.2'
gem 'sinatra-contrib', '1.3.1'
gem 'sinatra-respond_to', '>= 0.8', :git => 'git://github.com/simon/sinatra-respond_to.git'
gem 'sinatra_more', :git => 'git@github.com:curbed/sinatra_more.git'

gem 'hiredis'
gem 'ohm', '1.0.2'
gem 'ohm-contrib', '1.0.1'
gem 'redis-rack-cache', '1.2'
gem 'geohash', :git => 'git://github.com/davetroy/geohash.git'
gem 'base32-crockford'

gem 'json'
gem 'oj', '1.2.8'

# gem 'activesupport', '3.2.3'
# gem 'mongo', '1.6.2'
# gem 'bson', '1.6.2'
# gem 'bson_ext', '1.6.2'
# gem 'mongo_mapper'
# gem 'asset_timestamps_cache'
# gem 'httparty'
# gem 'curb'
# gem 'cssmin'
