source 'http://rubygems.org'

gem 'sinatra', '1.3.2'
gem 'sinatra-contrib', '1.3.1'
gem 'sinatra-respond_to', '>= 0.8', :git => 'git://github.com/simon/sinatra-respond_to.git'
gem 'activesupport', '3.1.3'
gem 'mongo', '1.5.2'
gem 'bson', '1.5.2'
gem 'bson_ext', '1.5.2'
gem 'mongo_mapper'
gem 'sinatra_more', :git => 'git@github.com:curbed/sinatra_more.git'
gem 'asset_timestamps_cache'
gem 'httparty'
gem 'cssmin'